### ISSUE TITLE
Deploy & Submit MU03 CGP on Mainnet

### ISSUE THREAD

**Issue by bowd** [mento-protocol/mento-deployment#103]
**Description**

After the MU03 CGP is drafted, we'll have to submit it on mainnet. 

**Acceptance Criteria**
- [x] set axlEUROC address for mainnet in dependencies https://celoscan.io/token/0x061cc5a2c863e0c1cb404006d559db18a34c762d
- [x] Generate proposal.json following [this guide](https://www.notion.so/Generating-a-proposal-json-for-Celo-Governance-Proposals-ecc815125cad4616b4ffa9e5670a240d?pvs=4)
- [ ] Submit it following the same guide

**Comment by philbow61** [comment]
https://github.com/philbow61/governance/tree/philbow61/mento-upgrade-03

**Comment by nvtaveras** [comment]
done https://celo.stake.id/#/proposal/133
