### ISSUE TITLE
Update Monitoring/Alerting to include new MU03 Exchanges/RateFeeds

### ISSUE THREAD

**Issue by philbow61** [mento-protocol/mento-deployment#113]
**Description:**
This ticket is about verifying that our Alerting/Monitoring tools include all updates from MU03. 
This includes:
- Dune Dashboards need to track new Exchanges 
- Aegis uses current contract addresses 
- Aegis tracks rate Feeds 
- Grafana alerts include new rate feeds 

**Acceptance Criteria:**
- [x] Monitoring infrastructure tracks MU03 changes
- [x] Alerting infrastructure tracks MU03 changes

🚧 
Blocked by:
- #103 

🚧

**Comment by philbow61** [comment]
aegis is deployed 
alerts track new rate feeds
new pools are tracked in dune dashboard

**Comment by baroooo** [comment]
LG 👍
