### ISSUE TITLE
Execute MU04 on Baklava

### ISSUE THREAD

**Issue by ninabarbakadze** [mento-protocol/mento-deployment#116]
**Description**

This Ticket is about executing MU04 on baklava. 
Before switching to the updated StableToken implementation we need to run the gas comparison script on the old system. 
After the CGP is executed we want to run the script again on the updated version. 

Blocked by 🚧 
- https://github.com/mento-protocol/mento-deployment/issues/121
- https://github.com/mento-protocol/mento-deployment/issues/114
- https://github.com/mento-protocol/mento-general/issues/297 

**Acceptance Criteria**
- [ ] Data from gas analysis before is gathered
- [x] The script is executed on Baklava
- [x] Fork tests are updated
- [x] Fork tests are green
- [ ] Data from gas analysis after is gathered

**Comment by nvtaveras** [comment]
Fork tests fixes https://github.com/mento-protocol/mento-core/pull/299
