### ISSUE TITLE
Draft and submit MU04 governance proposal on mainnet

### ISSUE THREAD

**Issue by ninabarbakadze** [mento-protocol/mento-deployment#119]
**Description**

In the latest stage we'd have to draft the proposal describing transactions being made and submit it on mainnet.

**Acceptance Criteria**
- [ ] Draft the MU04 CGP
- [ ] Generate proposal.json of the transactions following [this guide](https://www.notion.so/Generating-a-proposal-json-for-Celo-Governance-Proposals-ecc815125cad4616b4ffa9e5670a240d?pvs=4)
- [ ] Submit it following the same guide

**Comment by bayological** [comment]
**Story Points: 3**
  [See the discussion](https://action.parabol.co/meet/rUsZMLc5BC/estimate/3) in Sprint Poker #​​2

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
