### ISSUE TITLE
Draft the MU04 forum post

### ISSUE THREAD

**Issue by philbow61** [mento-protocol/mento-deployment#128]
**Description:**
This Ticket is about writing a forum post that informs the community about the coming changes of MU04 and explains the transactions of the CGP.

**Acceptance Criteria:**
- [ ] draft MU04 forum post

**Comment by bayological** [comment]
**Story Points: 3**
  [See the discussion](https://action.parabol.co/meet/rUsZMLc5BC/estimate/4) in Sprint Poker #​​2

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by philbow61** [comment]
draft of the forum post: 
https://www.notion.so/MU04-forum-post-8895228e51d84b169b5ee57304d799d5?pvs=4

**Comment by bayological** [comment]
Reviewed this, and it looks fine to me. 👍

**Comment by nvtaveras** [comment]
✅
