### ISSUE TITLE
Execute xKES deployment script on Alfajores

### ISSUE THREAD

**Issue by bowd** [mento-protocol/mento-deployment#172]

**Comment by bowd** [comment]
**Story Points: 2**
  [See the discussion](https://action.parabol.co/meet/wpkdF7I6E8/estimate/3) in Sprint Poker #​​40

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by bayological** [comment]
Deployed address - https://explorer.celo.org/alfajores/address/0x1E0433C1769271ECcF4CFF9FDdD515eefE6CdF92/contracts#address-tabs
