### ISSUE TITLE
Add token allocation recipients and final merkle tree

### ISSUE THREAD

**Issue by nvtaveras** [mento-protocol/mento-deployment#175]
** Description **

This was supposed to be done as part of https://github.com/mento-protocol/mento-core/issues/405, however there are still some discussions around the final recipient addresses for the token distribution as well as some changes being made to the final snapshots, so we had to move forward without them.

Once those are signed-off, update the mento-deployment repo once again with the final recipient addresses and the final snapshot, to make one last alfajores deployment.

** Acceptance Criteria **

- [ ] Recipient addresses updated for the token allocation
- [ ] Final merkle tree updated
- [ ] Update the tree in Airgrab UI

**Comment by bowd** [comment]
**Story Points: 2**
  [See the discussion](https://action.parabol.co/meet/wpkdF7I6E8/estimate/1) in Sprint Poker #​​40

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by baroooo** [comment]
**Story Points: 2**
  [See the discussion](https://action.parabol.co/meet/wAVe5Zqeqs/estimate/2) in Sprint Poker #​​41

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*
