### ISSUE TITLE
CGP - Add PUSO gas currency checks

### ISSUE THREAD

**Issue by bayological** [mento-protocol/mento-deployment#203]
**Description**

Create scripts to do the following:
- [ ] Gas currency checks (Check in with 0xOracle)

Put script somewhere so we can reuse it.

**Comment by bayological** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Planning-65b8ace7a595330035ca810b/issues/mento-protocol/mento-deployment/203?planning-poker) with Zenhub @baroooo @chapati23 @denviljclarke @nvtaveras @philbow61 @RyRy79261

**Comment by RyRy79261** [comment]
What is meant by `Gas currency checks` here?

**Comment by RyRy79261** [comment]
Creating a scripts repo here:
https://github.com/mento-protocol/mento-scripts
