### ISSUE TITLE
Move testnet protocol ownership back to Celo governance

### ISSUE THREAD

**Issue by baroooo** [mento-protocol/mento-deployment#225]
#### Description
Since we now have two more stable tokens to be created before the MU08 execution on Celo, we should transfer the ownership of the testnet contracts back to the Celo governance to enable testing of the governance proposals using the Celo governance.
This can be achieved by slight modification(switch mento governance and celo governance addresses) to the MU08 and running it on Alfajores

#### Acceptance Criteria
- [x] Alfajores contracts are owned by the Celo governance again

**Comment by denviljclarke** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Planning-65b8ace7a595330035ca810b/issues/mento-protocol/mento-deployment/225?planning-poker) with Zenhub @baroooo @chapati23 @nvtaveras @philbow61 @RyRy79261

**Comment by nvtaveras** [comment]
Transferred back https://alfajores.celoscan.io/tx/0xb20390196080e908fc3e89f4fe691debdc9ea622dd1a628c464b2212c304f8c8#eventlog
