### ISSUE TITLE
Improve Alfajores CGP passing

### ISSUE THREAD

**Issue by bowd** [mento-protocol/mento-deployment#37]
### Description

The current setup, which follows cLabs guidelines, requires Bogdan to port-forward to an Alfajores validator-0 in order to pass proposals. During a cursory investigation, it looks like validator-0 doesn't have that much Celo locked and used for voting, therefore CGPs should be quite easy to pass by creating an address that has enough funds locked (potentially from the community fund). That way the setup would be identical to the one used for Baklava and remove the special cases.

However before going forward we this we should touch base with cLabs (potentially Gaston Ponti), and discuss how to solve this issue. 

Related sidequest: return the Baklava Celo "borrowed" by mento into the "voter1" private key (stored in gcloud) to the LLC account. Bogdan note: I think I already unlocked and withdrew all the Celo for this account, but I'm not sure I also sent it back.

### Acceptance criteria

- [ ] We have discussed the option with cLabs and come to an agreement.
- [ ] We have an Alfajores "voter" account with enough Celo locked in order to pass a proposal (similar to Baklava LLC account).
- [ ] The account PK is stored in gcloud.
- [ ] Our tooling is updated so that CGPs on Alfajores use this account.

**Comment by ninocomputer** [comment]
This issue is currently on hold because the 2 people I was in contact with (Valentin and Ponti) aren't directly agreeing to us creating and funding the voter address. The feedback I got was that they were gonna discuss it with the team and get back to us. I'll follow up again this week.
