### ISSUE TITLE
Create a USDC/cUSD pool in Baklava

### ISSUE THREAD

**Issue by bowd** [mento-protocol/mento-deployment#4]
**Description**

After deploying the dummy USDC token, we need to create a USDC/cUSD pool in Mento. The exchange should use the USDC/USD Oracle rates as a reference price (see the identifier for the pair in the [Oracle runbook](https://www.notion.so/Mento-Oracles-runbook-445b3fa6897544cf9eb53e859d7b7df9#a013838bab0747fda469f3d116cfd31e)) 

**Acceptance Criteria**
- [x] Governance proposal script is updated to include the USDC/cUSD pool
- [x] The governance proposal is simulated to ensure that adding the pool actually works

**Comment by ninocomputer** [comment]
👀
