### ISSUE TITLE
Craft a proposal.json and markdown file for phase1-patch1

### ISSUE THREAD

**Issue by bowd** [mento-protocol/mento-deployment#47]
**Description**

The CGP submission process requires a proposal to be merged in the celo-org/governance repo. This proposal has both a markdown file explaining the proposal and a JSON encoded version of the proposal. This task covers generating that JSON proposal from our tooling and creating the MD file that describes the changes.

In order to generate the proposal based on our foundry script you can follow the steps provided in [this comment](https://github.com/mento-protocol/mento-deployment/blob/7df26c3238c2d3231c47c614853c577c796b9810/bin/cgp-yaml-to-json.sh).

**Useful Links**

- [draft proposal](https://github.com/celo-org/governance/blob/main/CGPs/cgp-template.md)
- [Repo for reference](https://github.com/celo-org/governance)
- [Celo docs](https://docs.celo.org/protocol/governance)

**Acceptance Criteria**

- [x] Governance proposal markdown file is created and accurately describes the changes
- [x] proposal.json is created with the smart contract calls to be executed
- [x] PR is created to add the JSON and MD files to the governance repo

**Comment by bowd** [comment]
**Story Points: 3**
  [See the discussion](https://action.parabol.co/meet/mF6n86kysM/estimate/8) in Sprint Poker #​​10

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by bayological** [comment]
PR: https://github.com/celo-org/governance/pull/264

**Comment by ninocomputer** [comment]
Looks good! Pr was merged!
