### ISSUE TITLE
Turn the proposal.json creation process into a runbook

### ISSUE THREAD

**Issue by bowd** [mento-protocol/mento-deployment#48]
**Description**

The Celo governance process requires the creation of a JSON file that outlines the smart contract calls needed for a proposal. Usually, the Celo CLI would be used to generate this file. However, it is incompatible with our tooling. As an alternative, we can use the output YAML from the CLI to create the JSON file with a helper script called [cgp-yaml-to-json.sh](https://github.com/mento-protocol/mento-deployment/blob/7df26c3238c2d3231c47c614853c577c796b9810/bin/cgp-yaml-to-json.sh). To clarify and streamline future processes, we should make a runbook with detailed steps to generate a proposal JSON file using this method.

**Acceptance Criteria**

- [x] Runbook for creating proposal.json is created
- [x] Runbook contains clear, step-by-step instructions

**Comment by bayological** [comment]
**Story Points: 2**
  [See the discussion](https://action.parabol.co/meet/mF6n86kysM/estimate/3) in Sprint Poker #​​10

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by bayological** [comment]
Runbook: https://www.notion.so/Generating-a-proposal-json-for-Celo-Governance-Proposals-ecc815125cad4616b4ffa9e5670a240d?pvs=4

**Comment by ninocomputer** [comment]
looks good 👍🏼 @bayological
