### ISSUE TITLE
Create MU01-CGP-Phase2 script

### ISSUE THREAD

**Issue by bayological** [mento-protocol/mento-deployment#58]
**Description**

To complete the phase 2 rollout, we need to update the existing phase 2 script. The script needs to do the following:

- [x] Create pool exchanges for cREAL/USDC and cEUR/USDC
- [x] Reset trading limits for all other pools according to the new phase config
- [x] Scale down the [reserveFraction](https://github.com/mento-protocol/mento-core/blob/develop/contracts/Exchange.sol#L401-L404) to half it's current value.

In order to transition to Phase2 we need to create a new CGP script in the MU01 upgrade governance folder.

**Acceptance Criteria**

- [x] Phase 2 script is updated to include the creation of the additional USDC pools

**Comment by philbow61** [comment]
we don't have the configuration for those pools yet but Nadiem is working on them

**Comment by ninocomputer** [comment]
Most of the logic was already added in the phase2 script, new pool configs were missing and I've added them [in this pr](https://github.com/mento-protocol/mento-deployment/pull/75)

**Comment by bayological** [comment]
Merged this to #66
