### ISSUE TITLE
Add configuration of the circuit breaker to MU01-CGP-Phase2

### ISSUE THREAD

**Issue by bayological** [mento-protocol/mento-deployment#66]
**Description**

Following the deployment of the new BreakerBox and MedianDeltaBreaker we'll need to reconfigure both for the existing and new rate feeds, cEUR/USDC & cREAL/USDC.

The new functionality that was introduced([Exponential moving average](https://github.com/mento-protocol/mento-core/issues/189) & [dependent rate feeds](https://github.com/mento-protocol/mento-core/issues/190)) require additional configuration beyond what was done for the phase 1 deployment. We will need to do the following:
- Configure the dependent rate feeds in the breaker box. 
- Add the smoothing factors for each rate feed to the MedianDeltaBreaker

The phase 2 CGP script should be updated to achieve this. In addition to the above this script should create the new pools.

**Acceptance Criteria**
- [x] Create pool exchanges for cREAL/USDC and cEUR/USDC
- [x]  Both the BreakerBox and MedianDeltaBreaker are reconfigured and support existing rate feeds and the newly added cEUR/USDC & cREAL/USDC
- [x] The rate feeds for cEUR/USDC & cREAL/USDC, dependent on USDC/USD, are correctly set up in the BreakerBox.
- [x] The MedianDeltaBreaker is correctly updated with the smoothing factors for each rate feed.
- [ ] Simulation tests pass
- [x] Breaker trading modes for both breakers , in circuitbreaker setup, should both be set to trading halted
- [x] Phase 2 script is updated to include the creation of the additional USDC pools

**Comment by bayological** [comment]
**Story Points: 3**
  [See the discussion](https://action.parabol.co/meet/nJxBsGtXS8/estimate/11) in Sprint Poker #​​12

  *Powered by [Parabol](https://www.parabol.co/resources/sprint-poker-meetings)*

**Comment by ninocomputer** [comment]
https://github.com/mento-protocol/mento-deployment/pull/75

**Comment by ninocomputer** [comment]
https://github.com/mento-protocol/mento-deployment/pull/83
