### ISSUE TITLE
Add script to deploy constant sum pricing module and BiPoolManager

### ISSUE THREAD

**Issue by bayological** [mento-protocol/mento-deployment#86]
**Description**
We need to launch a new version of the contract due to an updated constant sum pricing module. Let's create a dedicated script specifically for deploying this module. This way, if any changes are needed for this module in the future, we can simply modify this script.

**Acceptance Criteria**
- Deploy scripts created and added to MU03 folder

**Comment by ninocomputer** [comment]
https://github.com/mento-protocol/mento-deployment/pull/88
