### ISSUE TITLE
Deploy new contracts and execute MU03 governance script on Baklava

### ISSUE THREAD

**Issue by bayological** [mento-protocol/mento-deployment#87]
**Description**

We need to execute the constant sum pricing module deployment script across all networks including mainnet.

**Acceptance Criteria**
- [x] All deployments are run on all networks
- [x] Execute governance script of Baklava
- [x] Run fork tests

**Comment by ninocomputer** [comment]
This issue is on hold until the config refactor and deployment checks are merged

**Comment by ninocomputer** [comment]
new bipoolmanager - https://explorer.celo.org/mainnet/address/0x9B64E8EaBD1a035b148cE970d3319c5C3Ad53EC3/contracts#address-tabs

**Comment by ninocomputer** [comment]
we'll have to pass the gov proposals again after patching sortedOracles
